### ISSUE TITLE
Menu entry needs to be edited in order to run the flatpak

### ISSUE THREAD

**Issue by pizzadude** [flathub/org.sonic3air.Sonic3AIR#1]
The menu entry needs to be edited in order to launch the flatpak.

Meaning, I have to change:

`Exec=/usr/bin/flatpak run --branch=stable --arch=x86_64 --command=sonic3air-launcher org.sonic3air.Sonic3AIR`

to

`Exec=flatpak run org.sonic3air.Sonic3AIR`

Probably same bug as https://github.com/flathub/io.github.hakuneko.HakuNeko/issues/1

**Comment by Kekun** [comment]
The problem was that unlike the Flatpak manifest, the desktop entry wasn't running the wrapper calling the launcher and the game, but only directly calling the launcher. Sadly I just fixed it before noticing that issue, closing.
